.TH NFACCT 8 "Dec 30, 2011" "" ""

.\" Man page written by Pablo Neira Ayuso <pablo@netfilter.org> (Dec 2011)

.SH NAME
nfacct \- command line tool to create/retrieve/delete accounting objects
.SH SYNOPSIS
.BR "nfacct command [name] [options]"
.SH DESCRIPTION
.B nfacct
is the command line tool that allows to manipulate the Netfilter's extended
accounting infrastructure.
.SH COMMANDS
These commands specify the action that nfacct performs. Only one of them can be
specified at any given time.
.TP
.BI "list "
List the existing accounting object in table.
.TP
.BI "add "
Add new accounting object.
.TP
.BI "delete "
Delete accounting object.
.TP
.BI "get "
Get existing accounting object.
.TP
.BI "flush "
Flush the entire table.
.TP
.BI "version "
Displays the version information.
.TP
.BI "help "
Displays the help message.
.SH OPTIONS
.TP
This tool also allows a couple of options with the get and list commands that are:
.TP
.BI "reset "
That atomically obtains and resets the counters.
.TP
.BI "xml "
That displays the output in XML format.
.PP
.SH SEE ALSO
.BR iptables (8)
.SH BUGS
Please, report them to netfilter-devel@vger.kernel.org or file a bug in
Netfilter's bugzilla (https://bugzilla.netfilter.org).
.SH AUTHORS
Pablo Neira Ayuso wrote and maintains the nfacct tool.
.PP
Man page written by Pablo Neira Ayuso <pablo@netfilter.org>.
